x-common-config: &common-config
  restart: no

services:
  backend:
    <<: *common-config
    volumes:
      - ./backend/pb_data:/pb/pb_data
      - ./backend/pb_migrations:/pb/pb_migrations
      - ./backend/pb_hooks:/pb/pb_hooks
